spring:
  cloud:
    stream:
      default-binder: kafka
      function:
        definition: receiveMessage, sendMessage
      bindings:
        sendMessage-out-0:
          destination: client-service-topic
        receiveMessage-in-0:
          destination: client-service-topic
      kafka:
        binder:
          brokers: localhost:9092
          autoCreateTopics: true
          minPartitionCount: 1
